name: Check linting

on: [pull_request]

jobs:
  lint_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@dehaat'
      - name: Install dependencies
        run: npm ci --only-production
      - name: Run ESLint
        run: npm run lint
      - name: Run TSLint
        run: npm run tslint
